### ISSUE TITLE
Breaks on references

### ISSUE THREAD

**Issue by danielleevandenbosch** [jonathanng/art_vandelay#1]
I can only assume some references need to be checked. Is it possible to late bind them? If not what are the early binding references?

**Comment by jonathanng** [comment]
Can you post a screenshot of the break?

**Comment by danielleevandenbosch** [comment]
![error](https://user-images.githubusercontent.com/20933248/29878232-f006c422-8d6f-11e7-98f6-5747aa053b1b.png)

**Comment by jonathanng** [comment]
You need to add some references. I added a Setup section in the Readme.

Let me know if you have any more issues.

**Comment by zygimantus** [comment]
I have similar issue on this project. I have added all the references, but still I am getting this error:

![paveikslas](https://user-images.githubusercontent.com/8781824/67488327-4d021000-f678-11e9-927b-0a6039e65581.png)

**Comment by jonathanng** [comment]
I just added the missing sub here:

e5ff38e5b6c105808ceff6cca9edb5f1e66e7a7a

**Comment by zygimantus** [comment]
Now that part is ok, but unzip sub has problems.

**Comment by jonathanng** [comment]
@zygimantus just added another file.

e77178fa72de2662234416e1e7dadaab7cca9ebf
